title: 海心漩
email: wefashe@qq.com
description: 我的个人小站；
baseurl:
url: "http://localhost:4000"



markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
safe: false

permalink:  date
plugins: ['jekyll-paginate']
paginate: 10
## paginate_path: "blog/page:num/"
paginate_path: "p/:num"


leancloud:
  enable: true
  app_id: FL9CNp1luHvcsY8iA0oim5qj-gzGzoHsz
  app_key: GBV7UfsAl4nm4kgQACl9y9Eb


deploy:
  type: git
  repo:
    github: https://github.com/wefashe/wefashe.github.io.git
    gitee: https://gitee.com/wefashe/wefashe.git
  bransh: master