title: 海心漩
email: wefashe@qq.com
description: 我的个人小站；
baseurl: ""
url: "http://localhost:4000/"



markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


permalink: /:year/:month/:day/:title.html
gems: ['jekyll-paginate']
paginate: 150
paginate_path: "blog/page:num/"



deploy:
  type: git
  repo:
    github: https://github.com/wefashe/wefashe.github.io.git
    gitee: https://gitee.com/wefashe/wefashe.git
  bransh: master